### ISSUE TITLE
Errors and / or unclear results when running prediction.py

### ISSUE THREAD

**Issue by aphelionz** [hackforthesea/whalematch#1]
*Edit*: I noticed that it writes the output jpg to `Data/OutputData/temp.jpg`. Makes sense, just took me a second. The output could still be a bit clearer though.

### Steps to reproduce

1. Clone the repo
2. Create a virtual environment: `virtualenv venv`
3. Activate the virtual environment: `source venv/bin/activate`
4. Install requirements: `pip install -r requirements.txt`
5. Running the program: `python predictions.py

The results for reach file in `images_to_test_with` are below. I can surmise what the results might mean but it would be good if it was more understandable. Also there may or may not be bugs with the `IndexErrors`

```
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale1069.jpg
Using TensorFlow backend.
2018-09-25 15:00:42.902024: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
 FMA                               
Traceback (most recent call last):
  File "prediction.py", line 105, in <module>
    alphabet = find_blowhole(list=result, dict=whale_types)
  File "prediction.py", line 93, in find_blowhole
    return decoded[0]
IndexError: list index out of range
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale1098.jpg
Using TensorFlow backend.
2018-09-25 15:00:49.616561: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
 FMA
Traceback (most recent call last):
  File "prediction.py", line 105, in <module>
    alphabet = find_blowhole(list=result, dict=whale_types)
  File "prediction.py", line 93, in find_blowhole
    return decoded[0]
IndexError: list index out of range
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale591
Using TensorFlow backend.
2018-09-25 15:00:58.815152: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
 FMA
Traceback (most recent call last):
  File "prediction.py", line 100, in <module>
    result = predict(trained_model=model, test_image='Data/OutputData/scaledoutput.jpg')
  File "prediction.py", line 65, in predict
    img = Image.open(input_filename)
  File "/home/mark/Projects/hackforthesea/whalematch/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'images_to_test_with/whale591'
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale591.jpg
Using TensorFlow backend.
2018-09-25 15:01:01.701612: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "prediction.py", line 105, in <module>
    alphabet = find_blowhole(list=result, dict=whale_types)
  File "prediction.py", line 93, in find_blowhole
    return decoded[0]
IndexError: list index out of range
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale598.jpg 
Using TensorFlow backend.
2018-09-25 15:02:25.032949: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
('The blowhole is: ', 'C')
(venv) ➜  whalematch git:(master) ✗ \python prediction.py -i images_to_test_with/whale695.jpg 
Using TensorFlow backend.
2018-09-25 15:02:31.411017: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
('The blowhole is: ', 'F')
```

**Comment by isaacvandor** [comment]
Hey @aphelionz Thanks for opening this. There is definitely an issue with all of the `IndexErrors` that I haven't worked out yet. It has to do with the way we're creating a dictionary of whales and then mapping a new image against that dictionary. I decided to wait on it until after the hackathon since Ocean Alliance might want to change the way that functionality works anyway to more closely resemble actual whales etc. rather than just a dictionary of the english alphabet. I'm going to look further into fixing it though.

**Comment by isaacvandor** [comment]
Hey @aphelionz Latest commit should fix the `IndexErrors` issue. I just updated the whale types dictionary to include every letter in the alphabet so a prediction won't be out of range anymore. Not recommended as a permanent fix though since we should be naming the whale types according to their actual names anyway

**Comment by aphelionz** [comment]
@isaacvandor Thanks!
